server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Esta línea es la MAGIA para Vue Router (Modo History)
        # Si un archivo no existe, redirige siempre al index.html
        try_files $uri $uri/ /index.html;
    }

    # Bloque para archivos de error estándar de nginx
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
